version: 1.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: oKifhsYzHVBJw8GIQ8S81pPe/AeXOCwmgjszFV3kaYb41xKzmWQ79H2VM1H1AsP07zsWB4oLyaX/9x1XdnyWI0D73W5u/ijS7LDoX5kGDQ4=