version: 1.0.0.{build}
branches:
  only:
  - master
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: nwrjmXxa07JLeZ64i9Gq3cTQI5XdFKyAuYj3L/cFHYlH47AW94sybqWFPgRtw0rJ
  artifact: /.*\.nupkg/
- provider: GitHub
  auth_token:
    secure: iXRTi0GXb0J+zxsiM3IBHjvGzHpn8Ml0bJSfjGrm/XQaL0LFb3RIKWEK/5j780/9
  artifact: /.*\.nupkg/
  draft: true
  force_update: true
  on:
    branch: master
